# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f43b17009d93db64f696df60fd423fb002145a1da570da5d4178eae9df77b8155e9c5f29d4d6c94540cfe66da3c4a07762189f7d37e1c65c9733078ed388c94f

test:
  secret_key_base: 87009a440a0f18b7b9f50e46269cf9aa1ff7614a5905b18403aaa347c0d5664bd2d6a2402225152dad0a9e6a35b54f888a417d7dbd77a9b0383269fcf56350f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
